### PR TITLE
Add filter components

### PR DESCRIPTION
**Pull request by xtine**
Filter components to the pattern library:
- Checkboxes #22 
- Dropdowns #23 
- Toggle buttons #24 
- Radio buttons #25 
- Search fields #26 
- Boolean search #27 
- Range field #28 

screen shot 2017-11-28 at 9 15 17 pm

### CODE REVIEW

**Comment by xtine** [comment]
@jenniferthibault: committed notes for all the filter components, and also reorganized the rest of the components into folders and gave lower cased labels for component titles that were capitalized.

**Comment by jenniferthibault** [comment]
This is _awesome_. I just added a commit to repair some of my own typos and grammar mistakes copied over from the documentation.

One last question, and an idea.

**Question**
- Is it possible to some way simulate the typeahead interaction for the type-ahead only and type-ahead + free text search filters? That's a big part of the interaction that's worth demonstrating to show how the feature works and looks while it's working. 😬 

**Idea**
What do you think about renaming the checkbox and toggle options to not include the parent category in their titles? Looking at the whole batch together, it makes sense to me to keep the item names short when they are in a parent folder, which is what happens in the other categories.

screen shot 2017-11-29 at 9 18 47 am

**Comment by jenniferthibault** [comment]
Whoop! One more.

Let's also remove the previously existing [Toggles](https://fec-pattern-library.app.cloud.gov/components/detail/toggles.html) and [Dropdowns](https://fec-pattern-library.app.cloud.gov/components/detail/dropdowns.html) from the component list in favor of them being grouped under Filters

We should move the existing instruction `If you need to align the panel to the right edge, use .dropdown__panel–right` into the `Notes` tab though, because that seems useful. For something like this, where this sort of implementation note is useful for each subcategory of Dropdowns (Single select, multi select, and multi select with suggestions) do you think we should repeat the note in each? I'm leaning yes, but would love your ideas.

**Comment by xtine** [comment]
- Typeahead demo is technically possible, but would take a fair amount of time to write some custom pattern library JavaScript to make it happen. An idea perhaps though, is to include an animated gif to demo it?
- I like the idea of renaming some of the filter components to be less redundant. Done.
- Removed non-filter Toggles and Dropdowns.

**Comment by jenniferthibault** [comment]
Got it, could you show me how you were thinking we'd add an animated gif? I think that could work but not sure where you're proposing it would go

**Pull request merged**
