### PR TITLE
Static docs build

### PR DESCRIPTION
**Pull request by xtine**
Added documentation of the `fractal build` command that builds a static viewable version of the docs and also the latest static build.

cc @noahmanger

### CODE REVIEW

**Comment by noahmanger** [comment]
Is there a reason to check in the generated files?

**Comment by xtine** [comment]
I'm thinking of the case if someone needs to view the Style Guide but doesn't have npm installed on their machine, they can just pull the repo down and view the pages.

**Comment by noahmanger** [comment]
Ah that's a good point. Is it an option to just host them online? Or do we not have that ability anymore?

**Comment by xtine** [comment]
Let me check on the possibility of hosting them online. Also it would be easier to host them online as static files than the node server. It just needs to be a base level url so the images work (they are all currently referenced as `/img/*`.

**Comment by xtine** [comment]
Because this design system is now going to be continuously deployed on cloud.gov (#3), no need for static docs build. Closing.

**Pull request closed without merging**
